### ISSUE TITLE
Adding nodes should use (typed) shortcut method

### ISSUE THREAD

**Issue by stof** [kevin-verschaeve/symfony-config-builder#3]
Adding a boolean node should use `booleanNode('name')` rather than `node('name', 'boolean')`. Same for other types.

**Comment by kevin-verschaeve** [comment]
can I ask why ? From the POV of code, adding the `node()` method is simpler

**Comment by stof** [comment]
well, it helps with types in the IDE (as the method is typed as `@return BooleanNodeDefinition`) and with discoverability.

Btw, you already to it for prototypes, where you use `->arrayPrototype()` rather than `prototype()` (and the typed shortcuts for prototypes are available in 3.3+ while shortcuts for nodes are there since the creation of the component in 2.0).

**Comment by stof** [comment]
Looking at the code, I was able to make this change without making the code more complex at all, thanks to the way Symfony named the methods.
